name = "multimode-studio"
license = "Unlicense"
licenselink = "https://unlicense.org"
description = "Multimode workspace theme inspired by text editors, game engines, DAWs and more."
homepage = "https://github.com/ioiototm/multimode-studio-hugo-theme"
author = "ioioto"
min_version = "0.120.0"